config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :product_suites
  resources :glossaries
  resources :settings, only: [:index, :edit, :show, :update]
  resources :projects

  get 'deploys/index'
  get 'about/cookies'

  devise_for :users, controllers: { registrations: 'registrations' }
  scope '/admin' do
    resources :users
  end

  root to: 'about#index'

  resources :candidate_organizations do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :products do
    get 'count', on: :collection
  end

  resources :building_blocks do
    get 'count', on: :collection
  end

  resources :sustainable_development_goals, only: [:index, :show] do
    get 'count', on: :collection
  end

  resources :sdg_targets, only: [:index, :show]

  resources :use_cases do
    get 'count', on: :collection
  end

  resources :workflows do
    get 'count', on: :collection
  end

  resources :deploys do
    get 'show_messages'
    post 'add_ssh_user'
  end

  resources :organizations do
    get 'count', on: :collection
  end

  resources :operator_services

  resources :audits, only: [:index]

  resources :locations do
    resources :organizations
  end

  resources :sectors do
    resources :organizations
    resources :use_cases
  end

  resources :contacts do
    resources :organizations
  end

  post '/add_filter', to: 'application#add_filter', as: :add_filter
  post '/remove_filter', to: 'application#remove_filter', as: :remove_filter
  post '/remove_all_filters', to: 'application#remove_all_filters', as: :remove_all_filters
  get '/get_filters', to: 'application#get_filters', as: :get_filters
  get '/agg_capabilities', to: 'organizations#agg_capabilities', as: :agg_capabilities
  get '/agg_services', to: 'organizations#agg_services', as: :agg_services
  get '/service_capabilities', to: 'organizations#service_capabilities', as: :service_capabilities
  get '/update_capability', to: 'organizations#update_capability', as: :update_capability

  get 'export', :to => 'organizations#export'
  get 'map_aggregators', :to => 'organizations#map_aggregators'
  get 'map', :to => 'organizations#map'
  get 'map_fs', :to => 'organizations#map_fs'
  get 'candidate_organization_duplicates', :to => 'candidate_organizations#duplicates'
  get 'contact_duplicates', :to => 'contacts#duplicates'
  get 'location_duplicates', :to => 'locations#duplicates'
  get 'sector_duplicates', :to => 'sectors#duplicates'
  get 'product_duplicates', :to => 'products#duplicates'
  get 'building_block_duplicates', :to => 'building_blocks#duplicates'
  get 'organization_duplicates', :to => 'organizations#duplicates'
  get 'use_case_duplicates', :to => 'use_cases#duplicates'
  get 'workflow_duplicates', :to => 'workflows#duplicates'
  get 'glossary_duplicates', :to => 'glossaries#duplicates'
  get 'product_suite_duplicates', :to => 'product_suites#duplicates'
  get 'deploys_refresh_list', :to => 'deploys#refresh_list'
  get 'project_duplicates', to: 'projects#duplicates'

  get 'productlist', :to => 'products#productlist', as: :productlist
  get 'productmap', :to => 'products#map'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/operator_service.rb
class OperatorService < ActiveRecord::Base
  belongs_to :location, foreign_key: 'locations_id'
  attr_accessor :country_list

  scope :name_contains, ->(name) { where('LOWER(name) like LOWER(?)', "%#{name}%") }

  def self.to_csv
    attributes = %w{id name country service}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |op_service|
        csv << [op_service.id, op_service.name, op_service.location.name, op_service.service]
      end
    end
  end
end

app/controllers/operator_services_controller.rb
class OperatorServicesController < ApplicationController
  before_action :set_operator_services, only: [:show, :edit, :update, :destroy]
  before_action :set_core_services

  # GET /operators
  # GET /operators.json
  def index
    if params[:without_paging]
      @operators = OperatorService.order(:name)
      authorize @operators, :view_allowed?
      return
    end

    @operators = OperatorService.select(:name).distinct.order(:name)
    !params[:search].nil? && @operators = @operators.name_contains(params[:search])
    authorize @operators, :view_allowed?
  end

  # GET /organizations/name
  # GET /organizations/name.json
  def show
    authorize OperatorService, :view_allowed?
  end

  # GET /organizations/new
  def new
    authorize OperatorService, :mod_allowed?
    @operator_service = OperatorService.new
  end

  # GET /organizations/name/edit
  def edit
    authorize @operator_services, :mod_allowed?
  end

  # POST /organizations
  # POST /organizations.json
  def create
    authorize OperatorService, :mod_allowed?
    operator_name = params[:operator_service][:name]

    selected_countries = []
    if (params[:selected_countries].present?)
      selected_countries = params[:selected_countries].keys.map(&:to_i)
    end

    selected_countries.each do |country|
      # create records for each core service in this geography
      @core_services.each do |service|
        new_service = OperatorService.new
        new_service.name = operator_name
        new_service.locations_id = country
        new_service.service = service
        new_service.save
      end
    end

    respond_to do |format|
        format.html { redirect_to operator_services_path,
                      flash: { notice: t('messages.model.created', model: t('model.organization').to_s.humanize) }}
        format.json { render :show, status: :created, location: @operator_service }
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    authorize @operator_services, :mod_allowed?

    if (params[:operator_service][:name] != @operator_services.first.name)
      # update the name for all records
      @operator_services.each do |service|
        service.name = params[:operator_service][:name]
        service.save
      end
    end

    selected_countries = []
    if (params[:selected_countries].present?)
      selected_countries = params[:selected_countries].keys.map(&:to_i)
    end

    # Remove any countries from operator services that were removed in the edit
    country_ids = @operator_services.pluck(:locations_id).uniq
    country_ids.each do |country|
      if !selected_countries.include?(country)
        destroy_services = OperatorService.where(name: @operator_services.first.name, locations_id: country).destroy_all
      end
    end

    selected_countries.each do |country|
      if !country_ids.include?(country)
        # create records for each core service in this geography
        @core_services.each do |service|
          new_service = OperatorService.new
          new_service.name = @operator_services.first.name
          new_service.locations_id = country
          new_service.service = service
          new_service.save
        end
      end
    end
  
    respond_to do |format|
        format.html { redirect_to operator_services_path,
                      flash: { notice: t('messages.model.updated', model: t('model.organization').to_s.humanize) }}
        format.json { render :show, status: :ok, location: @operator_services }
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    authorize @operator_services, :mod_allowed?

    # Remove all countries from operator services 
    country_ids = @operator_services.pluck(:locations_id).uniq
    country_ids.each do |country|
      destroy_services = OperatorService.where(name: @operator_services.first.name, locations_id: country).destroy_all
    end

    respond_to do |format|
      format.html { redirect_to operator_services_path,
                    flash: { notice: t('messages.model.deleted', model: t('model.operator_services').to_s.humanize) }}
      format.json { head :no_content }
    end
  end

  def map
    #@organizations = Organization.eager_load(:locations)
    #authorize @organizations, :view_allowed?
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_operator_services
      @operator_services = OperatorService.where(name: params[:id])
      @operator_service = @operator_services.first
      @operator_name = @operator_service.name
      @operator_countries = Location.where(id: @operator_services.select('locations_id'))
      @curr_operator = OperatorService.new
      @curr_operator.name = @operator_name
      @curr_operator.country_list = @operator_countries

      # The countries_services list is not currently needed. Keeping the code here in case we 
      #  want to add it later
      # @countries_services = { }
      # @operator_countries.each do |country|
      #   curr_services = @operator_services.where(locations_id: country.id)
      #   service_list = []
      #   curr_services.each do |service|
      #     service_list.push(service.service)
      #   end
      #   @countries_services[country.name] = service_list
      # end
    end

    def set_core_services
      @core_services = ['Airtime', 'API', 'HS', 'Mobile-Internet', 'Mobile-Money', 'Ops-Maintenance', 'OTT', 'SLA', 'SMS', 'User-Interface', 'USSD', 'Voice'];
    end

end

app/views/operator_services/_form.html.erb
  <%= form_for(operator_service, :url => operator_service_path(operator_service.name), :method=>:put) do |form| %>

    <fieldset class="form-label-group">
      <%= form.text_field :name, id: :operator_name,
                          class: "form-control", placeholder: t('view.general.name') %>
      <%= form.label :name, t('view.general.name') %>
    </fieldset>


    <h6 class="bg-secondary text-white border rounded p-3 mb-0">
      <%= t('model.country').to_s.pluralize.humanize %> 
    </h6>
    <fieldset class="form-label-group mt-2">
      <input type="text" id="country-search" class="form-control"
             placeholder="<%= t('view.multi-select.assigned.label', model: t('model.country').to_s.pluralize) %>" />
      <label for="country-search">
        <%= t('view.multi-select.assigned.label', model: t('model.country').to_s.pluralize) %>
      </label>
    </fieldset>
    <div class="row">
      <div class="col-12">
        <span id="base-selected-countries" class="selected-element badge badge-secondary px-1 mb-1">
          <span class="text-label"></span>
          <a onclick="remove(this);" style="cursor: pointer;">
            <i class="fas fa-trash-alt"></i>
          </a>
          <input type="hidden"/>
        </span>
      </div>
    </div>

    <fieldset class="float-right mt-4">
      <%= form.submit t('view.general.submit'), :class => "btn btn-primary" %>
      <%= link_to t('view.general.back'), "javascript:window.history.back()", :class => 'btn btn-outline-secondary' %>
    </fieldset>
  <% end %>

<script>
  <% operator_service.country_list.order("name").each do |location| %>
    addLocation('<%= location.id %>', '<%= location.name %>');
  <% end %>
  var countryAutoComplete = autoComplete("/locations.json?without_paging=true", addLocation)
  $('#base-selected-countries').hide();
  $("#country-search").autocomplete(countryAutoComplete);
</script>

app/views/operator_services/_newform.html.erb
  <%= form_with(model: operator_service, multipart: true, local: true) do |form| %>

    <fieldset class="form-label-group">
      <%= form.text_field :name, id: :operator_name,
                          class: "form-control", placeholder: t('view.general.name') %>
      <%= form.label :name, t('view.general.name') %>
    </fieldset>


    <h6 class="bg-secondary text-white border rounded p-3 mb-0">
      <%= t('model.country').to_s.pluralize.humanize %> 
    </h6>
    <fieldset class="form-label-group mt-2">
      <input type="text" id="country-search" class="form-control"
             placeholder="<%= t('view.multi-select.assigned.label', model: t('model.country').to_s.pluralize) %>" />
      <label for="country-search">
        <%= t('view.multi-select.assigned.label', model: t('model.country').to_s.pluralize) %>
      </label>
    </fieldset>
    <div class="row">
      <div class="col-12">
        <span id="base-selected-countries" class="selected-element badge badge-secondary px-1 mb-1">
          <span class="text-label"></span>
          <a onclick="remove(this);" style="cursor: pointer;">
            <i class="fas fa-trash-alt"></i>
          </a>
          <input type="hidden"/>
        </span>
      </div>
    </div>

    <fieldset class="float-right mt-4">
      <%= form.submit t('view.general.submit'), :class => "btn btn-primary" %>
      <%= link_to t('view.general.back'), "javascript:window.history.back()", :class => 'btn btn-outline-secondary' %>
    </fieldset>
  <% end %>

<script>
  var countryAutoComplete = autoComplete("/locations.json?without_paging=true", addLocation)
  $('#base-selected-countries').hide();
  $("#country-search").autocomplete(countryAutoComplete);
</script>

app/views/operator_services/edit.html.erb
<h5 class="border rounded bg-secondary text-white p-3">
  <%= t('view.general.title.edit', model: t('model.operator_services')) %>
</h5>
<%= render 'form', operator_service: @curr_operator %>

app/views/operator_services/index.html.erb
<p class="text-success"><%= flash[:notice] %></p>
<p class="text-danger"><%= flash[:error] %></p>

<% if user_signed_in? && policy(OperatorService).mod_allowed? %>
  <%= link_to t('view.general.create'), new_operator_service_path, :class => 'btn btn-outline-secondary float-left ml-1' %>
<% end %>
<div class="float-right pb-2">
  <%= form_tag(operator_services_path, :method => "get", id: "search-form", class: "form-inline") do %>
  <%= text_field_tag :search, params[:search],
      placeholder: t('view.general.search-placeholder', model: t('model.operator_services').to_s.pluralize),
      class: "form-control" %>
  <div class="input-group-append">
    <%= submit_tag t('view.general.search'), :class => "btn btn-secondary" %>
  </div>
<% end %>
</div>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th><%= t('view.general.name') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operators.each do |operator| %>
      <tr>
        <td><%= operator.name %></td>
        <td class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
             aria-haspopup="true" aria-expanded="false">
            <%= t('view.general.action') %>
          </a>
          <div class="dropdown-menu">
            <%= link_to t('view.general.view'), operator_service_path(operator.name), :class =>"dropdown-item"  %>
            <% if user_signed_in? && policy(operator).mod_allowed? %>
              <%= link_to t('view.general.edit'), edit_operator_service_path(operator.name), :class =>"dropdown-item"  %>
              <div class="dropdown-divider"></div>
              <%= link_to t('view.general.delete'), operator_service_path(operator.name), method: :delete, data: { confirm: t('view.general.delete-confirmation') }, :class =>"dropdown-item" %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/operator_services/new.html.erb
<h5 class="border rounded bg-secondary text-white p-3">
  <%= t('view.general.title.create', model: t('model.operator_services')) %>
</h5>
<%= render 'newform', operator_service: @operator_service %>

app/views/operator_services/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
  <h5 class="card-header bg-secondary text-white">
    Operator: <%= @operator_name %>
  </h5>
  <div class="card-body">
    <p class="float-right mb-0 mr-2" >
      <%= link_to 'Back', operator_services_path, :class => "card-link" %>
      <% if user_signed_in? && policy(@curr_operator).mod_allowed? %>
        <%= link_to 'Edit', edit_operator_service_path(@curr_operator.name), :class => "card-link" %>
      <% end %>
    </p>
  </div>
  <div class="mt-4">
    <div class="border rounded bg-secondary text-white clearfix border card-header">
      <h5 class="float-left mb-0"><%= t('model.location').to_s.pluralize.humanize %></h5>
    </div>
    <% if @operator_countries.count > 0 %>
      <div class="row mb-2">
        <% @operator_countries.order("name").each do |country| %>
          <div class="col-6 col-lg-4 mt-2">
            <div class="card h-100">
              <div class="card-body py-2">
                <p class="card-text text-muted" style="flex: 1"><%= country.name %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <div>
</div>