config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :product_suites
  resources :glossaries
  resources :settings, only: [:index, :edit, :show, :update]
  resources :projects

  get 'deploys/index'
  get 'about/cookies'

  devise_for :users, controllers: { registrations: 'registrations' }
  scope '/admin' do
    resources :users
  end

  root to: 'about#index'

  resources :candidate_organizations do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :products do
    get 'count', on: :collection
  end

  resources :building_blocks do
    get 'count', on: :collection
  end

  resources :sustainable_development_goals, only: [:index, :show] do
    get 'count', on: :collection
  end

  resources :sdg_targets, only: [:index, :show]

  resources :use_cases do
    get 'count', on: :collection
  end

  resources :workflows do
    get 'count', on: :collection
  end

  resources :deploys do
    get 'show_messages'
    post 'add_ssh_user'
  end

  resources :organizations do
    get 'count', on: :collection
  end

  resources :operator_services

  resources :audits, only: [:index]

  resources :locations do
    resources :organizations
  end

  resources :sectors do
    resources :organizations
    resources :use_cases
  end

  resources :contacts do
    resources :organizations
  end

  post '/add_filter', to: 'application#add_filter', as: :add_filter
  post '/remove_filter', to: 'application#remove_filter', as: :remove_filter
  post '/remove_all_filters', to: 'application#remove_all_filters', as: :remove_all_filters
  get '/get_filters', to: 'application#get_filters', as: :get_filters
  get '/agg_capabilities', to: 'organizations#agg_capabilities', as: :agg_capabilities
  get '/agg_services', to: 'organizations#agg_services', as: :agg_services
  get '/service_capabilities', to: 'organizations#service_capabilities', as: :service_capabilities
  get '/update_capability', to: 'organizations#update_capability', as: :update_capability

  get 'export', :to => 'organizations#export'
  get 'map_aggregators', :to => 'organizations#map_aggregators'
  get 'map', :to => 'organizations#map'
  get 'map_fs', :to => 'organizations#map_fs'
  get 'candidate_organization_duplicates', :to => 'candidate_organizations#duplicates'
  get 'contact_duplicates', :to => 'contacts#duplicates'
  get 'location_duplicates', :to => 'locations#duplicates'
  get 'sector_duplicates', :to => 'sectors#duplicates'
  get 'product_duplicates', :to => 'products#duplicates'
  get 'building_block_duplicates', :to => 'building_blocks#duplicates'
  get 'organization_duplicates', :to => 'organizations#duplicates'
  get 'use_case_duplicates', :to => 'use_cases#duplicates'
  get 'workflow_duplicates', :to => 'workflows#duplicates'
  get 'glossary_duplicates', :to => 'glossaries#duplicates'
  get 'product_suite_duplicates', :to => 'product_suites#duplicates'
  get 'deploys_refresh_list', :to => 'deploys#refresh_list'
  get 'project_duplicates', to: 'projects#duplicates'

  get 'productlist', :to => 'products#productlist', as: :productlist
  get 'productmap', :to => 'products#map'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_activefilter.html.erb
<div id="active-filter" class="row">
  <div class="col-9">
    <ul class="list-group ml-3">
      <% all_filters.each do |filter| %>
        <% if session.key? filter %>
          <% @filters_exist = true %>
          <li id="<%= filter %>" class="list-group-item">
            <%= format_filter(filter) %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div class="col-3">
    <% if @filters_exist %>
    <a id="share-link" href="#" class="float-right" data-toggle="tooltip" data-placement="bottom" data-original-title="<%= t('view.active-filter.share-link-tooltip') %>"><%= t('view.active-filter.share-link') %></a>
    <div class="float-right"></div>
    <textarea class="copytextarea hidden"></textarea>
    <button id="doclick" class="hidden"></button>
    <% end %>
  </div>
</div>

app/views/shared/_breadcrumb.html.erb
<% #  style="top: 102px; position: sticky; z-index: 1024;" %>
<nav id="breadcrumb" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="/products">
        <%= t('view.breadcrumb.home') %>
      </a>
    </li>
    <% breadcrumbs = build_breadcrumbs(params) %>
    <li class="breadcrumb-item">
      <a href='/<%= breadcrumbs[:base_path] %>'>
        <%= breadcrumbs[:base_label] %>
      </a>
    </li>
    <% if params[:id] && params[:action] == 'show'%>
      <li class="breadcrumb-item active" aria-current="page">
        <%= breadcrumbs[:id_label] %>
      </li>
    <% else %>
      <li class="breadcrumb-item" aria-current="page">
        <a href='/<%= breadcrumbs[:id_path] %>'>
          <%= breadcrumbs[:id_label] %>
        </a>
      </li>
    <% end %>
  </ol>
</nav>

app/views/shared/_footer.html.erb
<footer id="footer">
  <ul class="icons sponsors">
    <li class="description">
      <a href="https://digitalimpactalliance.org">The Digital Impact Alliance</a>
      <%= t('view.footer.tag-line') %>
    </li>
    <li><%= image_tag "unf-logo.png", :alt => "United Nations Foundation" %></li>
    <li><%= image_tag "bill-n-melinda-logo.png", :alt => "Bill and Melinda Gates Foundation" %></li>
    <li><%= image_tag "sweden-logo.png", :alt => "Swedish International Development Cooperation Agency" %></li>
    <li><%= image_tag "usaid-logo.png", :alt => "USAID" %></li>
  </ul>
  <ul class="copyright">
    <li>
      <a target="_blank" rel="noreferrer noopener" rel="noreferrer noopener" href="https://digitalimpactalliance.org/contact-us/ict4sdg/"
         class="fas fa-envelope" style="text-decoration:none;">
      </a>
      <a target="_blank" rel="noreferrer noopener" href="https://digitalimpactalliance.org/contact-us/ict4sdg/"
          style="text-decoration:none;">
         <%= t('view.footer.ict4sdg-updates') %>
      </a>
    </li>
    <li>
      <a target="_blank" rel="noreferrer noopener" href="https://forum.osc.dial.community"
         class="fab fa-forumbee" style="text-decoration:none;">
      </a>
      <a target="_blank" rel="noreferrer noopener" href="https://forum.osc.dial.community"
         style="text-decoration:none;">
         <%= t('view.footer.osc-forum') %>
      </a>
    </li>
    <li>
      <a target="_blank" rel="noreferrer noopener" href="https://gitlab.com/dial/t4d-product-backlog/product-registry"
         class="fas fa-share-alt" style="text-decoration:none;">
      </a>
      <a target="_blank" rel="noreferrer noopener" href="https://gitlab.com/dial/t4d-product-backlog/product-registry"
         style="text-decoration:none;">
         <%= t('view.footer.gitlab') %>
      </a>
    </li>
  </ul>
  <ul class="copyright">
    <li><%= t('view.footer.dial-social-media') %>
    <li>
      <a target="_blank" rel="noreferrer noopener" href="https://twitter.com/DIAL_Community"
         class="fab fa-twitter" style="text-decoration:none;">
      </a>
    </li>
    <li>
      <a target="_blank" rel="noreferrer noopener" href="https://facebook.com/DigitalImpactAlliance"
         class="fab fa-facebook" style="text-decoration:none;">
      </a>
    </li>
    <li>
      <a target="_blank" rel="noreferrer noopener" href="https://www.instagram.com/dial_community"
         class="fab fa-instagram" style="text-decoration:none;">
      </a>
    </li>
  </ul>
  <ul class="copyright">
    <li>
      <a target="_blank" rel="noreferrer noopener" href="https://fontawesome.com/"><%= t('view.footer.fa-icons') %></a>
    </li>
    <li>
      <a target="_blank" rel="noreferrer noopener" href="https://www.globalgoals.org/"><%= t('view.footer.sdg-icons') %></a>
    </li>
  </ul>
  <ul class="copyright">
    <li>© 2019 Digital Impact Alliance</li>
    <li>
      <a target="_blank" rel="noreferrer noopener" href="http://www.digitalimpactalliance.org/privacy-policy/"><%= t('view.footer.privacy-policy') %></a>
    </li>
  </ul>
</footer>

app/views/shared/_help.html.erb
<style>
.step {
  display: none;
}

.step-indicator {
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbbbbb;
  border: none;
  border-radius: 50%;
  display: inline-block;
  opacity: 0.5;
}

.step-indicator.active {
  opacity: 1;
}
</style>

<div class="modal fade" id="help-modal" tabindex="-1" role="dialog" aria-labelledby="Help Modal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-body bg-secondary">
        <div class="step">
          <%= image_tag('help/filter-help.png', class: 'align-middle', style: 'width: 45rem;') %>
        </div>
        <div class="step">
          <%= image_tag('help/filter-active.png', class: 'align-middle', style: 'width: 45rem;') %>
        </div>
        <div class="step">
          <%= image_tag('help/filter-counter.png', class: 'align-middle', style: 'width: 45rem;') %>
        </div>
        <div class="text-center pt-2">
          <span class="step-indicator"></span>
          <span class="step-indicator"></span>
          <span class="step-indicator"></span>
        </div>
        <fieldset class="text-center pt-2">
          <button type="button" id="prevButton" class="btn btn-light">Previous</button>
          <button type="button" id="nextButton" class="btn btn-primary">Next</button>
        </fieldset>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidenav.html.erb
<div class="about-nav">
    <div id="intro" class="side-element text-muted nav-highlight" data-toggle="tooltip" data-placement="top" data-original-title="<%= t('view.about.intro') %>" >&#x25cf;</div>
    <div id="overview" class="side-element text-muted" data-toggle="tooltip" data-placement="top" data-original-title="<%= t('view.about.overview') %>" >&#x25cf;</div>
    <div id="donors" class="side-element text-muted" data-toggle="tooltip" data-placement="top" data-original-title="<%= t('view.about.donors') %>" >&#x25cf;</div>
    <div id="policy" class="side-element text-muted" data-toggle="tooltip" data-placement="top" data-original-title="<%= t('view.about.policy_partners') %>">&#x25cf;</div>
    <div id="ministers" class="side-element text-muted" data-toggle="tooltip" data-placement="top" data-original-title="<%= t('view.about.ministers_specialists') %>">&#x25cf;</div>
</div>

<script>

    var introDot = $('#intro');
    var overviewDot = $('#overview');
    var donorDot = $('#donors');
    var policyDot = $('#policy');
    var ministerDot = $('#ministers');

    $("#intro").click(function() {
        $('html,body').animate({
            scrollTop: $("#intro_section").offset().top - 100},
            'slow');
    });

    $("#overview").click(function() {
        $('html,body').animate({
            scrollTop: $("#overview_section").offset().top - 100},
            'slow');
    });

    $("#donors").click(function() {
        $('html,body').animate({
            scrollTop: $("#donor_section").offset().top - 100},
            'slow');
    });

    $("#policy").click(function() {
        $('html,body').animate({
            scrollTop: $("#policy_section").offset().top - 100},
            'slow');
    });

    $("#ministers").click(function() {
        $('html,body').animate({
            scrollTop: $("#implement_section").offset().top - 100},
            'slow');
    });

    // Only do this on the landing page
      
    $(window).scroll(function(){
       if ($("#overview_section").length > 0) {
          currPos = $(window).scrollTop() + 500

          if (currPos < $("#overview_section").position().top) {
              introDot.addClass('nav-highlight');
              overviewDot.removeClass('nav-highlight');
              donorDot.removeClass('nav-highlight');
              policyDot.removeClass('nav-highlight');
              ministerDot.removeClass('nav-highlight');
          }
          if ((currPos > $("#overview_section").position().top) && (currPos < $("#donor_section").position().top)) {
              introDot.removeClass('nav-highlight');
              overviewDot.addClass('nav-highlight');
              donorDot.removeClass('nav-highlight');
              policyDot.removeClass('nav-highlight');
              ministerDot.removeClass('nav-highlight');
          }
          if ((currPos > $("#donor_section").position().top) && (currPos < $("#policy_section").position().top)) {
              introDot.removeClass('nav-highlight');
              overviewDot.removeClass('nav-highlight');
              donorDot.addClass('nav-highlight');
              policyDot.removeClass('nav-highlight');
              ministerDot.removeClass('nav-highlight');
          }

          if ((currPos > $("#policy_section").position().top) && (currPos < $("#implement_section").position().top)) {
              introDot.removeClass('nav-highlight');
              overviewDot.removeClass('nav-highlight');
              donorDot.removeClass('nav-highlight');
              policyDot.addClass('nav-highlight');
              ministerDot.removeClass('nav-highlight');
          }

          if (currPos > $("#implement_section").position().top) {
              introDot.removeClass('nav-highlight');
              overviewDot.removeClass('nav-highlight');
              donorDot.removeClass('nav-highlight');
              policyDot.removeClass('nav-highlight');
              ministerDot.addClass('nav-highlight');
          }
        }
    });

</script>

app/views/shared/_summarynav.html.erb
<div id="summary-nav" class="row mb-2 bg-dark">
  <div class="col-12">
    <div class="list-group w-100 flex-fill list-group-horizontal bg-transparent">
      <li class="list-group-item w-100 text-center bg-transparent">
        <%= link_to sustainable_development_goals_path do %>
          <% if current_page?(:controller => 'sustainable_development_goals', :action => 'index') %>
            <span class="w-100 btn btn-warning"><%= t('model.sdg').upcase.pluralize %>
          <% else %>
            <span class="w-100 btn btn-secondary"><%= t('model.sdg').upcase.pluralize %>
          <% end %>
            <span id="sdg-badge" class="badge badge-light">--</span>
          </span>
        <% end %>
      </li>
      <li class="list-group-item w-100 text-center bg-transparent">
        <%= link_to use_cases_path do %>
          <% if current_page?(:controller => 'use_cases', :action => 'index') %>
            <span class="w-100 btn btn-warning"><%= t('model.use-case').titlecase.pluralize %>
          <% else %>
            <span class="w-100 btn btn-secondary"><%= t('model.use-case').titlecase.pluralize %>
          <% end %>
          <span id="use-case-badge" class="badge badge-light">--</span>
          </span>
        <% end %>
      </li>
      <li class="list-group-item w-100 text-center bg-transparent">
        <%= link_to workflows_path do %>
          <% if current_page?(:controller => 'workflows', :action => 'index') %>
            <span class="w-100 btn btn-warning"><%= t('model.workflow').titlecase.pluralize %>
          <% else %>
            <span class="w-100 btn btn-secondary"><%= t('model.workflow').titlecase.pluralize %>
          <% end %>
          <span id="workflow-badge" class="badge badge-light">--</span>
          </span>
        <% end %>
      </li>
      <li class="list-group-item w-100 text-center bg-transparent">
        <%= link_to building_blocks_path do %>
          <% if current_page?(:controller => 'building_blocks', :action => 'index') %>
            <span class="w-100 btn btn-warning"><%= t('model.building-block').titlecase.pluralize %>
          <% else %>
            <span class="w-100 btn btn-secondary"><%= t('model.building-block').titlecase.pluralize %>
          <% end %>
          <span id="bb-badge" class="badge badge-light">--</span>
          </span>
        <% end %>
      </li>
      <li class="list-group-item w-100 text-center bg-transparent">
        <%= link_to products_path do %>
          <% if current_page?(:controller => 'products', :action => 'index') %>
            <span class="w-100 btn btn-warning"><%= t('model.product').titlecase.pluralize %>
          <% else %>
            <span class="w-100 btn btn-secondary"><%= t('model.product').titlecase.pluralize %>
          <% end %>
          <span id="product-badge" class="badge badge-light">--</span>
          </span>
        <% end %>
      </li>
      <li class="list-group-item w-100 text-center bg-transparent">
        <%= link_to organizations_path do %>
          <% if current_page?(:controller => 'organizations', :action => 'index') %>
            <span class="w-100 btn btn-warning"><%= t('model.organization').titlecase.pluralize %>
          <% else %>
            <span class="w-100 btn btn-secondary"><%= t('model.organization').titlecase.pluralize %>
          <% end %>
          <span id="org-badge" class="badge badge-light">--</span>
          </span>
        <% end %>
      </li>
    </div>
  </div>
</div>

app/views/shared/_topnav.html.erb
<div id="header-outer" data-turbolinks-permanent>
  <div id="header-widget">
    <nav id="header" class="navbar navbar-expand-lg navbar-dark fixed-top">
      <div class="container-fluid">
        <a href="/">
          <%= image_tag "logo-dial.png", :alt => "DIAL Logo", :height => "86px" %>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <% if (policy(current_user).index?) %>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle mt-2" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                     aria-haspopup="true" aria-expanded="false">
                    <strong><%= t('view.header.admin-data') %></strong>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <%= link_to t('model.contact').to_s.pluralize.titlecase, contacts_path, :class => 'dropdown-item' %>
                    <%= link_to t('model.location').to_s.pluralize.titlecase, locations_path, :class => 'dropdown-item' %>
                    <%= link_to t('model.project').to_s.pluralize.titlecase, projects_path, :class => 'dropdown-item' %>
                    <%= link_to t('model.sector').to_s.pluralize.titlecase, sectors_path, :class => 'dropdown-item' %>
                    <%= link_to t('model.user').to_s.pluralize.titlecase, users_path, :class => 'dropdown-item' %>
                    <div class="dropdown-divider"></div>
                    <%= link_to t('model.candidate-organization').to_s.pluralize.titlecase, candidate_organizations_path, :class => 'dropdown-item' %>
                    <% if (policy(current_user).mni?) %>
                      <%= link_to t('model.operator_services').to_s.pluralize.titlecase, operator_services_path, :class => 'dropdown-item' %>
                    <% end %>
                    <%= link_to t('model.product-suite').to_s.pluralize.titlecase, product_suites_path, :class => 'dropdown-item' %>
                    <div class="dropdown-divider"></div>
                    <%= link_to t('model.deploys').to_s.pluralize.titlecase, deploys_path, :class => 'dropdown-item' %>
                  </div>
                </li>
              <% elsif (policy(current_user).mni?) %>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle mt-2" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <strong><%= t('view.header.mni-data') %></strong>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                      <%= link_to t('model.operator_services').to_s.pluralize.titlecase, operator_services_path, :class => 'dropdown-item' %>
                  </div>
                </li>
              <% elsif (policy(current_user).ict4sdg?) %>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle mt-2" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <strong><%= t('view.header.ict4sdg-data') %></strong>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <%= link_to t('model.project').to_s.pluralize.titlecase, projects_path, :class => 'dropdown-item' %>
                    <%= link_to t('model.sector').to_s.pluralize.titlecase, sectors_path, :class => 'dropdown-item' %>
                  </div>
                </li>
              <% elsif (policy(current_user).principle?) %>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle mt-2" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <strong><%= t('view.header.principle-data') %></strong>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <%= link_to t('model.contact').to_s.pluralize.titlecase, contacts_path, :class => 'dropdown-item' %>
                    <%= link_to t('model.location').to_s.pluralize.titlecase, locations_path, :class => 'dropdown-item' %>
                    <%= link_to t('model.sector').to_s.pluralize.titlecase, sectors_path, :class => 'dropdown-item' %>
                  </div>
                </li>
              <% end %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle-avatar" data-toggle="dropdown" href="#" role="button">
                  <div class="avatar-circle">
                    <span class="initials">
                      <%= current_user.email[0].upcase %>
                    </span>
                  </div>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                  <%= link_to t('view.header.profile'), edit_user_registration_path, :class => 'dropdown-item' %>
                  <%= link_to t('model.glossary').to_s.pluralize.titlecase, glossaries_path, :class => 'dropdown-item' %>
                  <a target="_blank" rel="noreferrer noopener" href="https://docs.osc.dial.community/projects/product-registry/en/latest/" class="dropdown-item">
                    <%= t('view.header.documentation') %>
                  </a>
                  <div class="dropdown-divider"></div>
                  <% if (policy(current_user).index?) %>   
                    <%= link_to t('model.setting').to_s.pluralize.titlecase, settings_path, :class => 'dropdown-item' %>
                  <% end %>
                  <%= link_to t('view.header.feedback'),
                              'mailto:incoming+dial-t4d-product-backlog-product-registry-9056306-issue-@incoming.gitlab.com',
                              target: '_blank', class: 'dropdown-item' %>
                  <%= link_to t('view.header.logout'), destroy_user_session_path, method: :delete, :class => 'dropdown-item' %>
                </div>
              </li>
            <% else %>
              <li>
                <strong><%= link_to t('view.header.sign-up'), new_user_registration_path, :class => 'nav-link' %></strong>
              </li>
              <li>
                <strong><%= link_to t('view.header.login'), new_user_session_path, :class => 'nav-link' %></strong>
              </li>
              <li>
                <a target="_blank" rel="noreferrer noopener" href="https://docs.osc.dial.community/projects/product-registry/en/latest/" class="nav-link">
                  <strong><%= t('view.header.documentation') %></strong>
                </a>
              </li>
              <li>
                <strong>
                  <%= link_to t('view.header.feedback'),
                              'mailto:incoming+dial-t4d-product-backlog-product-registry-9056306-issue-@incoming.gitlab.com',
                              target: '_blank', class: 'nav-link' %>
                </strong>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</div>