config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :product_suites
  resources :glossaries
  resources :settings, only: [:index, :edit, :show, :update]
  resources :projects

  get 'deploys/index'
  get 'about/cookies'

  devise_for :users, controllers: { registrations: 'registrations' }
  scope '/admin' do
    resources :users
  end

  root to: 'about#index'

  resources :candidate_organizations do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :products do
    get 'count', on: :collection
  end

  resources :building_blocks do
    get 'count', on: :collection
  end

  resources :sustainable_development_goals, only: [:index, :show] do
    get 'count', on: :collection
  end

  resources :sdg_targets, only: [:index, :show]

  resources :use_cases do
    get 'count', on: :collection
  end

  resources :workflows do
    get 'count', on: :collection
  end

  resources :deploys do
    get 'show_messages'
    post 'add_ssh_user'
  end

  resources :organizations do
    get 'count', on: :collection
  end

  resources :operator_services

  resources :audits, only: [:index]

  resources :locations do
    resources :organizations
  end

  resources :sectors do
    resources :organizations
    resources :use_cases
  end

  resources :contacts do
    resources :organizations
  end

  post '/add_filter', to: 'application#add_filter', as: :add_filter
  post '/remove_filter', to: 'application#remove_filter', as: :remove_filter
  post '/remove_all_filters', to: 'application#remove_all_filters', as: :remove_all_filters
  get '/get_filters', to: 'application#get_filters', as: :get_filters
  get '/agg_capabilities', to: 'organizations#agg_capabilities', as: :agg_capabilities
  get '/agg_services', to: 'organizations#agg_services', as: :agg_services
  get '/service_capabilities', to: 'organizations#service_capabilities', as: :service_capabilities
  get '/update_capability', to: 'organizations#update_capability', as: :update_capability

  get 'export', :to => 'organizations#export'
  get 'map_aggregators', :to => 'organizations#map_aggregators'
  get 'map', :to => 'organizations#map'
  get 'map_fs', :to => 'organizations#map_fs'
  get 'candidate_organization_duplicates', :to => 'candidate_organizations#duplicates'
  get 'contact_duplicates', :to => 'contacts#duplicates'
  get 'location_duplicates', :to => 'locations#duplicates'
  get 'sector_duplicates', :to => 'sectors#duplicates'
  get 'product_duplicates', :to => 'products#duplicates'
  get 'building_block_duplicates', :to => 'building_blocks#duplicates'
  get 'organization_duplicates', :to => 'organizations#duplicates'
  get 'use_case_duplicates', :to => 'use_cases#duplicates'
  get 'workflow_duplicates', :to => 'workflows#duplicates'
  get 'glossary_duplicates', :to => 'glossaries#duplicates'
  get 'product_suite_duplicates', :to => 'product_suites#duplicates'
  get 'deploys_refresh_list', :to => 'deploys#refresh_list'
  get 'project_duplicates', to: 'projects#duplicates'

  get 'productlist', :to => 'products#productlist', as: :productlist
  get 'productmap', :to => 'products#map'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  include OrganizationsHelper

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_action :set_current_user, only: [:edit, :update, :destroy]
  before_action :set_core_services, only: [:show, :edit, :update, :new]

  # GET /organizations
  # GET /organizations.json
  def index
    if params[:without_paging]
      @organizations = Organization
      !params[:mni_only].nil? && @organizations = @organizations.where('is_mni is true') 
      !params[:sector_id].nil? && @organizations = @organizations.joins(:sectors).where('sectors.id = ?', params[:sector_id])
      !params[:search].nil? && @organizations = @organizations.name_contains(params[:search])
      @organizations = @organizations.eager_load(:sectors, :locations).order(:name)
      authorize @organizations, :view_allowed?
      return
    end

    @organizations = search_organizations
    params[:search].present? && @organizations = @organizations.name_contains(params[:search])
    authorize @organizations, :view_allowed?
  end

  def count
    organizations = search_organizations
    authorize organizations, :view_allowed?
    render json: organizations.count
  end

  def search_organizations
    organizations = Organization.all.order(:slug)

    endorser_only = sanitize_session_value 'endorser_only'
    aggregator_only = sanitize_session_value 'aggregator_only'
    countries = sanitize_session_values 'countries'
    products = sanitize_session_values 'products'
    sectors = sanitize_session_values 'sectors'
    years = sanitize_session_values 'years'
    orgs = sanitize_session_values 'organizations'
    origins = sanitize_session_values 'origins'

    !orgs.empty? && organizations = organizations.where('id in (?)', orgs)

    product_list = Product.all
    if !origins.empty?
      product_list = product_list.where('id in (select product_id from products_origins where origin_id in (?))', origins)
    end
    if !products.empty?
      product_list = product_list.where('id in (?)', products)
    end
    puts "COUNT: "+product_list.count.to_s

    if (endorser_only && aggregator_only)
      organizations = organizations.where(is_endorser: true).or(organizations.where(is_mni: true))
    else
      endorser_only && organizations = organizations.where(is_endorser: true)
      aggregator_only && organizations = organizations.where(is_mni: true)
    end
    !countries.empty? && organizations = organizations.joins(:locations).where('locations.id in (?)', countries)
    (!products.empty? || !origins.empty?) && organizations = organizations.joins(:products).where('products.id in (?)', product_list.ids)
    !sectors.empty? && organizations = organizations.joins(:sectors).where('sectors.id in (?)', sectors)
    !years.empty? && organizations = organizations.where('extract(year from when_endorsed) in (?)', years)
    organizations
  end

  def export
    export_contacts = params[:export_contacts].downcase == "true" ? true : false
    send_data(
      export_with_params(export_contacts),
      filename: "Endorsing Organizations.xls",
      type: "application/vnd.ms-excel"
    )
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    authorize @organization, :view_allowed?
  end

  # GET /organizations/new
  def new
    authorize Organization, :mod_allowed?
    @organization = Organization.new
    @organization_description = OrganizationDescription.new
  end

  # GET /organizations/1/edit
  def edit
    authorize @organization, :mod_allowed?
  end

  # POST /organizations
  # POST /organizations.json
  def create
    authorize Organization, :mod_allowed?
    @organization = Organization.new(organization_params)
    @organization.set_current_user(current_user)

    if (params[:selected_sectors].present?)
      params[:selected_sectors].keys.each do |sector_id|
        @sector = Sector.find(sector_id)
        @organization.sectors.push(@sector)
      end
    end

    if (params[:contact].present?)
      contact = Contact.new
      contact.name = params[:contact][:name]
      contact.email = params[:contact][:email]
      contact.title = params[:contact][:title]

      contact_slug = slug_em(params[:contact][:name])
      dupe_count = Contact.where(slug: contact_slug).count
      if dupe_count > 0
        first_duplicate = Contact.slug_starts_with(contact_slug).order(slug: :desc).first
        contact.slug = contact_slug + generate_offset(first_duplicate).to_s
      else
        contact.slug = contact_slug
      end

      organization_contact = OrganizationsContact.new
      organization_contact.contact = contact
      organization_contact.started_at = Time.now.utc

      @organization.organizations_contacts << organization_contact
    end

    if (params[:selected_countries].present?)
      params[:selected_countries].keys.each do |location_id|
        location = Location.find(location_id)
        @organization.locations.push(location)
      end
    end

    if (params[:selected_products].present?)
      params[:selected_products].keys.each do |product_id|
        product = Product.find(product_id)
        @organization.products.push(product)
      end
    end

    if params[:selected_projects].present?
      params[:selected_projects].keys.each do |project_id|
        project = Project.find(project_id)
        @organization.projects.push(project)
      end
    end

    if (params[:office_id].present?)
      office = Location.find(params[:office_id])
      if (office)
        @organization.locations.push(office)
      end
    end

    if (params[:office_magickey].present?)
      auth_token = authenticate_user
      geocoded_location = geocode(params[:office_magickey], auth_token)
      geocoded_location.save
      @organization.locations.push(geocoded_location)
    end

    if (params[:logo].present?)
      uploader = LogoUploader.new(@organization, params[:logo].original_filename, current_user)
      begin
        uploader.store!(params[:logo])
      rescue StandardError => e
        @organization.errors.add(:logo, t('errors.messages.extension_whitelist_error'))
      end
      @organization.set_image_changed(params[:logo].original_filename)
    end

    respond_to do |format|
      if @organization.errors.none? && @organization.save

        if organization_params[:organization_description].present?
          @organization_description = OrganizationDescription.new
          @organization_description.organization_id = @organization.id
          @organization_description.locale = I18n.locale
          @organization_description.description = JSON.parse(organization_params[:organization_description])
          @organization_description.save
        end

        format.html do
          redirect_to @organization, flash: {
            notice: t('messages.model.created', model: t('model.organization').to_s.humanize)
          }
        end
        format.json { render :show, status: :created, location: @organization }
      else
        error_message = ''
        @organization.errors.each do |_, err|
          error_message = err
        end
        format.html { redirect_to new_organization_url, flash: { error: error_message } }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    authorize @organization, :mod_allowed?
    if (params[:selected_sectors].present?)
      sectors = Set.new
      params[:selected_sectors].keys.each do |sector_id|
        sector = Sector.find(sector_id)
        sectors.add(sector)
      end
      @organization.sectors = sectors.to_a
    end

    if params[:selected_contacts].present?
      @organization.organizations_contacts.each do |organization_contact|
        contact_id = organization_contact.contact.id
        unless params[:selected_contacts].include?(contact_id.to_s)
          organization_contact.update(ended_at: Time.now.utc)
        end
      end

      organization_contacts = []
      params[:selected_contacts].each do |selected_contact|
        organization_contact = @organization.organizations_contacts.find_by(contact_id: selected_contact)
        if organization_contact && organization_contact.ended_at.nil?
          next
        end

        organization_contact = OrganizationsContact.new
        organization_contact.contact = Contact.find(selected_contact)
        organization_contact.started_at = Time.now.utc
        organization_contacts.push(organization_contact)
      end

      @organization.organizations_contacts << organization_contacts
    else
      OrganizationsContact.where(organization_id: @organization.id)
                          .update(ended_at: Time.now.utc)
    end

    locations = Set.new
    if (params[:selected_countries].present?)
      params[:selected_countries].keys.each do |location_id|
        location = Location.find(location_id)
        locations.add(location)
      end
    end

    products = Set.new
    if (params[:selected_products].present?)
      params[:selected_products].keys.each do |product_id|
        product = Product.find(product_id)
        products.add(product)
      end
    end
    @organization.products = products.to_a

    projects = Set.new
    if params[:selected_projects].present?
      params[:selected_projects].keys.each do |project_id|
        project = Project.find(project_id)
        projects.add(project)
      end
    end
    @organization.projects = projects.to_a

    if (params[:office_ids].present?)
      params[:office_ids].keys.each do |office_id|
        office = Location.find(office_id)
        locations.add(office)
      end
    end

    if (params[:office_magickeys].present?)
      auth_token = authenticate_user
      params[:office_magickeys].keys.each do |office_magickey|

app/helpers/organizations_helper.rb
module OrganizationsHelper
  def export_with_params(with_contacts)
    book = Spreadsheet::Workbook.new
    sheet = book.create_worksheet :name => 'Endorsing Organizations'

    sheet.row(0).height = 20
    format = Spreadsheet::Format.new :weight => :bold, :size => 14
    sheet.row(0).default_format = format

    column_length = [0, 10, 0, 0, 0, 0]
    columns = ["Organization", "Year", "Link", "Geographic Locations", "Sector Specialization", "Office Locations"]
    column_offset = 0

    if with_contacts
      column_length.insert(3, 0, 0, 0)
      columns.insert(3, "Contact Name", "Contact Title", "Contact Email")
      column_offset = 3
    end

    sheet.row(0).concat columns

    organizations = Organization.where(is_endorser: true).order(:name)

    x = 0
    organizations.each do |organization|
      if (column_length[0] < organization.name.length)
        column_length[0] = organization.name.length
      end

      if (column_length[2] < organization.website.length)
        column_length[2] = organization.website.length
      end

      contact_name = ''
      contact_title = ''
      contact_email = ''
      if with_contacts
        contact_name = organization.contacts.map{ |contact| contact.name }.join(", ")
        if (column_length[3] < contact_name.length)
          column_length[3] = contact_name.length
        end

        contact_title = organization.contacts.map{ |contact| contact.title }.join(", ")
        if (column_length[4] < contact_title.length)
          column_length[4] = contact_title.length
        end

        contact_email = organization.contacts.map{ |contact| contact.email }.join(", ")
        if (column_length[5] < contact_email.length)
          column_length[5] = contact_email.length
        end
      end

      country_name = organization.locations.select {|location| location.location_type != 'point'}.map{|location| location.name}.join(", ")
      if (column_length[3 + column_offset] < country_name.length)
        column_length[3 + column_offset] = country_name.length
      end

      sector_name = organization.sectors.map{ |sector| sector.name }.join(",")
      if (column_length[4 + column_offset] < sector_name.length)
        column_length[4 + column_offset] = sector_name.length
      end

      office = organization.locations.select {|location| location.location_type == 'point'}.pop
      if (!office.nil? && column_length[5 + column_offset] < office.name.length)
        column_length[5 + column_offset] = office.name.length
      end

      row_data = [organization.name, organization.when_endorsed.strftime("%m/%d/%Y"),
          organization.website.downcase.strip, 
          country_name, sector_name, office.nil? ? "" : office.name]

      if with_contacts
        row_data.insert(3, contact_name, contact_title, contact_email)
      end

      sheet.row(x += 1).concat row_data
    end

    column_length.each.with_index do |c, index|
      sheet.column(index).width = c
    end

    toret = StringIO.new
    book.write toret
    return toret.string
  end
end

app/views/organizations/_filter.html.erb
    <div class="form-row">
      <div class="col-12 mb-3">
        <fieldset class="form-label-group">
          <%= text_field_tag "search", params[:search],
              placeholder: t('view.general.name'),
              class: "form-control" %>
          <%= label_tag "name", t('view.general.name') %>
        </fieldset>
      </div>
    </div>
    
      <div class="col-12 mb-3">
        <%= label_tag "sectors", t('model.sector').to_s.pluralize.humanize %>
        <%= collection_select(nil, "sectors",
                              Sector.all.order(:name), :id, :name,
                              { selected: params[:sectors] },
                              { multiple: true, class: 'custom-select' }) %>
      </div>
    </div>
    <div class="form-row">
      <div class="col-12 mb-3">
        <%= label_tag "products", t('model.product').to_s.pluralize.humanize %>
        <%= collection_select(nil, "products",
                              Product.all.order(:name), :id, :name,
                              { selected: params[:products] },
                              { multiple: true, class: 'custom-select' }) %>
      </div>
      <div class="col-12 mb-3">
        <%= label_tag "countries" %>
        <%= collection_select(nil, "countries",
                              Location.where.not(location_type: 'point').order(:name), :id, :name,
                              { selected: params[:countries] },
                              { multiple: true, class: 'custom-select' }) %>
      </div>
    </div>
    <div class="float-right">
      <button id="filter-toggle" type="button" class="btn btn-secondary"
              data-toggle="collapse" data-target="#filter-options"
              aria-expanded="false" aria-controls="filter-options">
        <%= t('view.organization.index.filter') %>
      </button>
    </div>

app/views/organizations/edit.html.erb
<% if @organization.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t('view.general.error', count: @organization.errors.count) %>
      <% @organization.errors.each do |attr, err| %>
        <%= err %>
      <% end %>
    </div>
  </div>
<% end %>
<h5 class="border rounded bg-secondary text-white p-3">
  <%= t('view.general.title.edit', model: t('model.organization')) %>
</h5>
<%= render 'form', organization: @organization, can_view_mni: @can_view_mni %>

app/views/organizations/index.html.erb
<p class="text-success"><%= flash[:notice] %></p>
<p class="text-danger"><%= flash[:error] %></p>

<div class="row">
  <div class="col-12">
    <div class="float-right">
      <% if user_signed_in? && policy(Organization).mod_allowed? %>
        <%= link_to t('view.general.create'), new_organization_path, :class => 'small mr-1' %>
        <span class="small mr-1">&nbsp;|</span>
        <%= link_to t('view.organization.index.view-audit'), audits_path(type: "Organization"), :class => 'small mr-1' %>
      <% end %>
      <% if !user_signed_in? %>
        <%= link_to t('view.general.create'), new_candidate_organization_path, :class => 'small mr-1' %>
      <% end %>
    </div>
    <%= form_with(url: export_path, :method => :get, :data => {remote: false}, :class => 'inline-form'  ) do | form | %>
      <%= form.hidden_field :export_contacts, :value => false %>
      <%= form.submit t('view.organization.index.export'), class: 'btn btn-link float-right px-1 py-0',
                      style: 'color: #fbab18; font-size: 80%;', data: { disable_with: false } %>
      <% if user_signed_in? && policy(Organization).export_contacts_allowed? %>
        <fieldset class="form-check" style="margin-top: -1px;">
          <%= form.check_box :export_contacts, {id: 'export_contacts', class: "form-check-input checkbox-align"}, true, false %>
          <label class="form-check-label text-muted" for="export_contacts" style="font-size: 80%;">
            <%= t('view.organization.index.export-option') %>
          </label>
        </fieldset>
      <% end %>
    <% end %>
  </div>
</div>

<div id="current-list">
<div class="row">
  <% @organizations.each do |organization| %>
    <div class="col-lg-5ths col-md-4 d-flex align-items-stretch mt-2">
      <div class="card index-card small">
        <div class="card-header bg-secondary text-white truncate-parent">
          <%= link_to organization.name, organization, class: 'truncate-text',
              'title' => organization.name, 'data-toggle' => 'tooltip', 'data-placement' => 'top' %>
        </div>
        <div class="model-logo">
          <%= link_to(organization) do %>
            <%= image_tag(organization.image_file, class: 'card-img-top align-middle', skip_pipeline: true) %>
          <% end %>
        </div>

        <div class="card-footer">
          <% if organization.website.present? %>
            <small>
              <a href="<%= "//" + organization.website %>" target="_blank" rel="noreferrer noopener">
                <%= t('view.organization.form.website').to_s.downcase %> &#x29c9;
              </a>
            </small>
            <br/>
          <% end %>
          <% if organization.is_endorser %>
          <small class="text-muted">
            <%= raw "#{image_tag('digiprins.png', width: 16)} #{t('view.organization.index.endorsed-date')}  #{organization.when_endorsed.year}" %>
          </small>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/organizations/show.html.erb
<p class="text-success"><%= flash[:notice] %></p>
<p class="text-danger"><%= flash[:error] %></p>

<div class="row">
  <div class="col-8 mb-2">
    <% if user_signed_in? && policy(Organization).mod_allowed? %>
      <%= link_to 'Delete this organization', @organization, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-outline-secondary float-left ml-1' %>
    <% end %>
  </div>
</div>
<div class="border rounded bg-secondary text-white clearfix border card-header">
  <h5 class="float-left mb-0">
    <%= "#{t('model.organization').to_s.humanize}:  #{@organization.name}" %>
    <% if @organization.is_endorser %>
      <i class="fas fa-check-circle text-success ml-2"></i>
    <% end %>
  </h5>
</div>

<div class="mt-2">
  <div class="row">
    <% if @organization.locations.find_all{|location| location.location_type == 'point'}.first %>
      <div class="col-lg-4 col-12">
        <div id="office" style="max-height: 28rem;"></div>
        <div id="office-popup" class="office-popup"></div>
      </div>
    <% end %>
    <div class="col-lg-8 col-12">
      <% if !@organization.aliases.empty? %>
        <p class="m-2">
          <strong><%= t('view.organization.form.other-names') %>:</strong>
          <ul>
            <% @organization.aliases.each{|other_name| %>
              <li><%= other_name %></li>
            <%}%>
          </ul>
        </p>
      <% end %>
      <% if !@organization.is_mni %>
        <p class="m-2">
          <strong><%= "#{t('view.organization.index.endorsed-date')}:" %></strong>
          <%= @organization.when_endorsed.nil? ? '' : @organization.when_endorsed.strftime("%m/%d/%Y") %>
        </p>
      <% end %>
      <% if !@organization_description.description.nil? && !@organization_description.description.empty? && @organization_description.description != "{}" %>
        <p class="m-2">
          <strong><%= t('view.organization.index.description') %>:</strong>
          <div id="product-viewer" class="wysiwyg-viewer"></div>
        </p>
      <% end %>
      <% if !@organization.website.nil? %>
        <p class="m-2">
          <strong><%= "#{t('view.organization.form.website')}:" %></strong>
          <%= link_to @organization.website.downcase.strip, "//#{@organization.website.downcase.strip}", target: :_blank %>
        </p>
      <% end %>
      <% if @organization.locations.find_all{|location| location.location_type == 'point'}.count > 1 %>
        <p class="m-2">
          <strong><%= "#{t('view.organization.show.other-offices')}:" %></strong>
          <ul>
          <% @organization.locations
                .find_all{ |location| location.location_type == 'point' }
                .drop(1)
                .each do |office| %>
            <li><%= office.name %></li>
          <% end %>
          </ul>
        </p>
      <% end %>
    </div>
  </div>
  <p class="float-right mb-0 mr-2" >
    <%= link_to 'Back', organizations_path, :class => "card-link" %>
    <% if user_signed_in? && policy(@organization).mod_allowed? %>
      <%= link_to t('view.general.edit'), edit_organization_path(@organization), :class => "card-link" %>
    <% end %>
  </p>
</div>

<% if user_signed_in? && (policy(Contact).view_allowed? || policy(@organization).mod_allowed?) %>
  <div class="mt-4">
    <div class="border rounded bg-secondary text-white clearfix border card-header">
      <h5 class="float-left mb-0"><%= t('model.contact').to_s.pluralize.humanize %></h5>
    </div>
    <% if @organization.organizations_contacts.count > 0 %>
      <div class="row">
        <% @organization.organizations_contacts.joins(:contact).order('contacts.name').each do |organization_contact| %>
          <div class="col-6 col-lg-4 mt-2">
            <div class="card h-100">
              <div class="card-body py-2">
                <h5 class="card-title"><%= link_to organization_contact.contact.name, organization_contact.contact %></h5>
                <h6 class="card-subtitle text-muted"><%= organization_contact.contact.email %></h6>
                <% if !organization_contact.contact.title.blank? %>
                  <p class="card-text"><%= organization_contact.contact.title %></p>
                <% end %>
                <p class="card-text text-muted small">
                <%= t('view.organization.show.with-org') %>:
                <%= organization_contact.started_at.nil? ?
                    t('view.organization.show.unknown') :
                    organization_contact.started_at.strftime("%m/%d/%Y") %>
                  -
                <%= organization_contact.ended_at.nil? ?
                    t('view.organization.show.current') :
                    organization_contact.ended_at.strftime("%m/%d/%Y") %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <%= t('view.general.not-available', model: t('model.organization'), multi: t('model.contact').to_s.pluralize) %>
    <% end %>
  </div>
<% end %>

<% if !@organization.is_mni ### Start for non-MNI data section. ### %>
<div class="mt-4">
  <div class="border rounded bg-secondary text-white clearfix border card-header">
    <h5 class="float-left mb-0"><%= t('model.sector').to_s.pluralize.humanize %></h5>
  </div>
  <% if @organization.sectors.count > 0 %>
    <div class="row">
      <% @organization.sectors.order("name").each do |sector| %>
        <div class="col-6 col-lg-4 mt-2">
          <div class="card h-100">
            <div class="card-body py-2">
              <p class="card-text text-muted" style="flex: 1"><%= link_to sector.name, sector %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <%= t('view.general.not-available', model: t('model.organization'), multi: t('model.sector').to_s.pluralize) %>
  <% end %>
</div>

<div class="mt-4">
  <div class="border rounded bg-secondary text-white clearfix border card-header">
    <h5 class="float-left mb-0"><%= t('model.product').to_s.pluralize.humanize %></h5>
  </div>
  <% if @organization.products.count > 0 %>
    <div class="row">
      <% @organization.products.each do |product| %>
        <div class="col-6 col-lg-4 mt-2">
          <div class="card flex-row">
            <%= link_to product do %>
              <%= image_tag(product.image_file, height: 75, class: 'card-image-top align-middle p-1') %>
            <% end %>
            <div class="card-body align-middle my-auto px-2 py-2">
              <%= link_to product.name, product %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <%= t('view.general.not-available', model: t('model.organization'), multi: t('model.product').to_s.pluralize) %>
  <% end %>
</div>

<div class="mt-4">
  <div class="border rounded bg-secondary text-white clearfix border card-header">
    <h5 class="float-left mb-0"><%= t('model.project').to_s.pluralize.humanize %></h5>
  </div>
  <% if @organization.projects.count > 0 %>
    <div class="row">
      <% @organization.projects.order("name").each do |project| %>
        <div class="col-6 col-lg-4 mt-2">
          <div class="card h-100">
            <div class="card-body py-2">
              <p class="card-text text-muted" style="flex: 1"><%= link_to project.name, project %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <%= t('view.general.not-available', model: t('model.organization'), multi: t('model.project').to_s.pluralize) %>
  <% end %>
</div>
<% end ### End for non-MNI data section. ### %>

<div class="mt-4">
  <div class="border rounded bg-secondary text-white clearfix border card-header">
    <h5 class="float-left mb-0"><%= t('model.country').to_s.pluralize.humanize %></h5>
  </div>
  <% if @organization.locations.select{|location| location.location_type != 'point'}.count > 0 %>
    <div class="row">
      <% @organization.locations.where.not(location_type: 'point').order("name").each do |country| %>
        <div class="col-6 col-lg-4 mt-2">
          <div class="card h-100">
            <div class="card-body py-2">
              <p class="card-text text-muted" style="flex: 1"><%= link_to country.name, country %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <%= t('view.general.not-available', model: t('model.organization'), multi: t('model.country').to_s.pluralize) %>
  <% end %>
</div>

<% if @organization.is_mni && @can_view_mni %>
  <div class="mt-4">
    <div class="border rounded bg-secondary text-white clearfix border card-header">
      <h5 class="float-left mb-0"><%= t('model.operator_services').to_s.pluralize.humanize %></h5>
    </div>
    <div id="orgId" style="display:none"><%= @organization.id %></div>
    <div id="agg-nav" class="card-body p-2 col-6 col-lg-4 mt-2 ml-4 accordion-section ">
      <div class="mni-accordion">
        <% @organization.locations.each do |country| %>
          <h3 class="country-list" id="<%= country.id %>"><%= country.name %></h3>
          <div>
            <div class="mni-accordion">
              <% @core_services.each do |service| %>
                <h3 class="country-service" id="<%= country.id %>_<%= service %>"><%= service %></h3>
                <div class="capability">
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<script>
  <%
    office = @organization.locations.find{|location| location.location_type == 'point'}
    if (office)
  %>
    function updateMapMarker() {
      setOfficeMarker('<%= @organization.name %>', '<%= office.name %>', '<%= office.points[0][1] %>', '<%= office.points[0][0] %>');
    }

    $(document).on('organizations#show:loaded', updateMapMarker)
  <% end %>
  
  <% if !@organization_description.description.nil? && !@organization_description.description.empty? && @organization_description.description != "{}" %>
    setUpViewer(<%= raw JSON.generate(@organization_description.description) %>) 
  <% end %>   
</script>