config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :product_suites
  resources :glossaries
  resources :settings, only: [:index, :edit, :show, :update]
  resources :projects

  get 'deploys/index'
  get 'about/cookies'

  devise_for :users, controllers: { registrations: 'registrations' }
  scope '/admin' do
    resources :users
  end

  root to: 'about#index'

  resources :candidate_organizations do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :products do
    get 'count', on: :collection
  end

  resources :building_blocks do
    get 'count', on: :collection
  end

  resources :sustainable_development_goals, only: [:index, :show] do
    get 'count', on: :collection
  end

  resources :sdg_targets, only: [:index, :show]

  resources :use_cases do
    get 'count', on: :collection
  end

  resources :workflows do
    get 'count', on: :collection
  end

  resources :deploys do
    get 'show_messages'
    post 'add_ssh_user'
  end

  resources :organizations do
    get 'count', on: :collection
  end

  resources :operator_services

  resources :audits, only: [:index]

  resources :locations do
    resources :organizations
  end

  resources :sectors do
    resources :organizations
    resources :use_cases
  end

  resources :contacts do
    resources :organizations
  end

  post '/add_filter', to: 'application#add_filter', as: :add_filter
  post '/remove_filter', to: 'application#remove_filter', as: :remove_filter
  post '/remove_all_filters', to: 'application#remove_all_filters', as: :remove_all_filters
  get '/get_filters', to: 'application#get_filters', as: :get_filters
  get '/agg_capabilities', to: 'organizations#agg_capabilities', as: :agg_capabilities
  get '/agg_services', to: 'organizations#agg_services', as: :agg_services
  get '/service_capabilities', to: 'organizations#service_capabilities', as: :service_capabilities
  get '/update_capability', to: 'organizations#update_capability', as: :update_capability

  get 'export', :to => 'organizations#export'
  get 'map_aggregators', :to => 'organizations#map_aggregators'
  get 'map', :to => 'organizations#map'
  get 'map_fs', :to => 'organizations#map_fs'
  get 'candidate_organization_duplicates', :to => 'candidate_organizations#duplicates'
  get 'contact_duplicates', :to => 'contacts#duplicates'
  get 'location_duplicates', :to => 'locations#duplicates'
  get 'sector_duplicates', :to => 'sectors#duplicates'
  get 'product_duplicates', :to => 'products#duplicates'
  get 'building_block_duplicates', :to => 'building_blocks#duplicates'
  get 'organization_duplicates', :to => 'organizations#duplicates'
  get 'use_case_duplicates', :to => 'use_cases#duplicates'
  get 'workflow_duplicates', :to => 'workflows#duplicates'
  get 'glossary_duplicates', :to => 'glossaries#duplicates'
  get 'product_suite_duplicates', :to => 'product_suites#duplicates'
  get 'deploys_refresh_list', :to => 'deploys#refresh_list'
  get 'project_duplicates', to: 'projects#duplicates'

  get 'productlist', :to => 'products#productlist', as: :productlist
  get 'productmap', :to => 'products#map'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  include Auditable

  attr_accessor :product_description

  has_one :product_assessment
  has_many :product_descriptions
  has_many :product_versions
  has_and_belongs_to_many :organizations, after_add: :association_add, before_remove: :association_remove
  has_and_belongs_to_many :sectors, join_table: :products_sectors, after_add: :association_add, before_remove: :association_remove
  has_and_belongs_to_many :building_blocks, join_table: :products_building_blocks, after_add: :association_add, before_remove: :association_remove
  has_and_belongs_to_many :origins, join_table: :products_origins, after_add: :association_add, before_remove: :association_remove

  has_many :products_sustainable_development_goals
  has_many :sustainable_development_goals, through: :products_sustainable_development_goals, after_add: :association_add, before_remove: :association_remove

  has_many :include_relationships, -> { where(relationship_type: 'composed')}, foreign_key: :from_product_id, class_name: 'ProductProductRelationship'
  has_many :includes, through: :include_relationships, source: :to_product, after_add: :association_add, before_remove: :association_remove

  has_many :interop_relationships, -> { where(relationship_type: 'interoperates')}, foreign_key: :from_product_id, class_name: 'ProductProductRelationship'
  has_many :interoperates_with, through: :interop_relationships, source: :to_product, after_add: :association_add, before_remove: :association_remove

  has_many :references, foreign_key: :to_product_id, class_name: 'ProductProductRelationship', after_add: :association_add, before_remove: :association_remove

  validates :name,  presence: true, length: { maximum: 300 }

  scope :name_contains, -> (name) { where("LOWER(products.name) like LOWER(?)", "%#{name}%")}
  scope :slug_starts_with, -> (slug) { where("LOWER(products.slug) like LOWER(?)", "#{slug}%\\_")}

  def self.first_duplicate(name, slug)
    find_by("name = ? OR slug = ? OR ? = ANY(aliases)", name, slug, name)
  end

  def image_file
    if File.exist?(File.join('public','assets','products',"#{slug}.png"))
      return "/assets/products/#{slug}.png"
    else
      return "/assets/products/prod_placeholder.png"
    end
  end

  def to_param  # overridden
    slug
  end

  def maturity_scores
    @osc_maturity = YAML.load_file("config/maturity_osc.yml")
    @digisquare_maturity = YAML.load_file("config/maturity_digisquare.yml")

    toret = {}
    if !self.product_assessment.nil?
      if self.product_assessment.has_osc
        @osc_maturity.each do |osc_maturity_category|
          total_possible_score = 0
          total_score = 0
          osc_maturity_category['items'].each do |item|
            if self.product_assessment.send('osc_' + item["code"].downcase)
              total_score += 1
            end
          end
          toret[osc_maturity_category['header']] = {}
          toret[osc_maturity_category['header']]['total'] = osc_maturity_category['items'].length
          toret[osc_maturity_category['header']]['score'] = total_score
        end
      end
      if self.product_assessment.has_digisquare
        @digisquare_maturity.each do |digisquare_maturity_category|
          cat_total = 0
          digisquare_maturity_category['sub-indicators'].each do |sub_indicator|
            next unless product_assessment.send(sub_indicator['code'])

            indicator = product_assessment.send(sub_indicator['code'])
            case indicator
            when ProductAssessment.digisquare_maturity_levels[:low]
              cat_total += -1
            when ProductAssessment.digisquare_maturity_levels[:medium]
              cat_total += 0
            when ProductAssessment.digisquare_maturity_levels[:high]
              cat_total += 1
            end
          end
          cat_score = 5 * (cat_total.to_f / digisquare_maturity_category['sub-indicators'].length) + 5
          toret[digisquare_maturity_category['core']] = cat_score
        end
      end
    end
    toret
  end

end

app/helpers/products_helper.rb
module ProductsHelper
  def digisquare_maturity_level_text(product_assessment, digisquare_maturity_yml_element)
    maturity_text = "Maturity indicator is not assigned."
    if (product_assessment)
      maturity_level = product_assessment.send(digisquare_maturity_yml_element["code"])
      case maturity_level
        when 'low'
          maturity_text = digisquare_maturity_yml_element["low"]
        when 'medium'
          maturity_text = digisquare_maturity_yml_element["medium"]
        when 'high'
          maturity_text = digisquare_maturity_yml_element["high"]
      end
    end
    maturity_text
  end

  def has_osc_assessment(product_assessment)
    has_assessment = false
    product_assessment.attributes.keys.select { |name| name.start_with?("osc") }.each do |key|
      has_assessment = product_assessment.send(key)
      if (has_assessment)
        break
      end
    end
    has_assessment
  end

  def has_digisquare_assessment(product_assessment)
    has_assessment = false
    product_assessment.attributes.keys.select { |name| name.start_with?("digisquare") }.each do |key|
      has_assessment = !product_assessment.send(key).nil?
      if (has_assessment)
        break
      end
    end
    has_assessment
  end

  def is_endorsed(product)
    is_endorsed = false
    product.organizations.each do |org|
      if (org.is_endorser)
        is_endorsed = true
      end
    end
    is_endorsed
  end

  def get_source_label(product)
    if (product.origins.size > 1)
      label = t("view.product.index.sources")
    else
      label = t("view.product.index.source")
    end
  end

  def get_row_popover(category,images)
    case category
    when "Building Blocks"
      header = t("view.product.index.footer_popover_bb")
    when "Compatibility"
      header = t("view.product.index.footer_popover_interop")
    when "Sustainable Development Goals"
      header = t("view.product.index.footer_popover_sdg")
    when "Maturity Models"
      header = t("view.product.index.footer_popover_maturity")
    end
    content = '<div class="card-header bg-secondary text-white">'+header+'</div>'
    content += '<div>'
    images.each do |image|
      if image["gradient"]
        content += '<div class="digisquare-gauge-med" title="'+image["tooltip"]+'">'
        content += '<p class="footer-score-large">'+image["filename"].to_s+'</p></div>'
      elsif image["osc"]
        content += '<div class="osc-med" title="'+image["tooltip"]+'">'
        content += '<p class="footer-score-large">'+image["filename"].to_s+'</p></div>'
      else
        if image["id"]
          content += link_to image_tag(image["filename"], class: 'popover-image', 'title' => image["tooltip"]), {action:'show', controller: image["controller"], id: image["id"]}
        else
          content += image_tag(image["filename"], class: 'popover-image', 'title' => image["tooltip"])
        end
      end
    end
    content += "</div>"
    content.html_safe
  end

  def get_footer_row(product, rownum)
    category = get_footer_category(product, rownum)
    images = build_footer_row(product, category)
    return category, images
  end

  def get_footer_category(product, rownum)
    category = "none"
    if (rownum == 1)
      if (product.building_blocks.size > 0)
        category = "Building Blocks"
      elsif (product.interoperates_with.size > 0) || (product.includes.size > 0)
        category = "Compatibility"
      elsif (product.sustainable_development_goals.size > 0)
        category = "Sustainable Development Goals"
      elsif (!product.product_assessment.nil?)
        category = "Maturity Models"
      end
    end
    if (rownum == 2)
      row1_cat = get_footer_category(product, 1)
      if ((product.interoperates_with.size > 0) || (product.includes.size > 0)) && (row1_cat == "Building Blocks")
        category = "Compatibility"
      elsif (product.sustainable_development_goals.size > 0) && ((row1_cat == "Building Blocks") || (row1_cat == "Compatibility"))
        category = "Sustainable Development Goals"
      elsif (!product.product_assessment.nil?) && ((row1_cat == "Building Blocks") || (row1_cat == "Compatibility") || (row1_cat == "Sustainable Development Goals"))
        category = "Maturity Models"
      end
    end
    if (rownum == 3)
      category = "sources"
    end
    category
  end

  def build_footer_row(product, category)
    images = []
    case category
    when "Building Blocks"
      product.building_blocks.each do |bb|
        tooltip = t("view.product.index.footer_bb_candidate") + bb.name + t("view.product.index.footer_bb")
        image = Hash["filename"=>bb.image_file, "tooltip"=>tooltip, "id"=>bb.id, "controller"=>"building_blocks"]
        images.push(image)
      end
    when "Compatibility"
      product.interoperates_with.each do |interop|
        tooltip = t("view.product.index.footer_interop") + interop.name
        image = Hash["filename"=>"/assets/products/"+interop.slug+".png", "tooltip"=>tooltip, "id"=>interop.id, "controller"=>"products"]
        images.push(image)
      end
      product.includes.each do |interop|
        tooltip = t("view.product.index.footer_interop") + interop.name
        image = Hash["filename"=>"/assets/products/"+interop.slug+".png", "tooltip"=>tooltip, "id"=>interop.id, "controller"=>"products"]
        images.push(image)
      end
    when "Sustainable Development Goals"
      product.sustainable_development_goals.sort { |x, y| x[:number].to_i <=> y[:number].to_i }.each do |sdg|
        tooltip = t("view.product.index.footer_sdg") + sdg.number.to_s + ": " + sdg.name
        image = Hash["filename"=>sdg.image_file, "tooltip"=>tooltip, "id"=>sdg.id, "controller"=>"sustainable_development_goals"]
        images.push(image)
      end
    when "Maturity Models"
      if (product.product_assessment.has_digisquare)
        digisquare_maturity = YAML.load_file("config/maturity_digisquare.yml")
        tooltip = t("view.product.index.footer_maturity_ds")
        image = Hash["filename"=>"origins/digital_square.png", "tooltip"=>tooltip]
        images.push(image)
        digisquare_maturity.each do |digisquare_category|
          score = product.maturity_scores[digisquare_category['core']].to_i
          tooltip = digisquare_category['core']
          image = Hash["filename"=>score, "tooltip"=>tooltip, "gradient"=>1]
          images.push(image)
        end
      end
      if (product.product_assessment.has_osc)
        osc_maturity = YAML.load_file("config/maturity_osc.yml")
        tooltip = t("view.product.index.footer_maturity_osc")
        image = Hash["filename"=>"origins/dial_osc.png", "tooltip"=>tooltip]
        images.push(image)
        score = 0
        total = 0
        osc_maturity.each do |osc_mat|
          score += product.maturity_scores[osc_mat['header']]['score'].to_i
          total += product.maturity_scores[osc_mat['header']]['total'].to_i
        end
        total_score = (score*10/total).round
        tooltip = t("view.product.index.footer_osc_score")
        image = Hash["filename"=>total_score, "tooltip"=>tooltip, "osc"=>1]
        images.push(image)
      end
    when "sources"
      if (product.origins.size == 0)
        tooltip = t("view.product.index.source_dial")
        image = Hash["filename"=>"origins/dial_osc.png", "tooltip"=>tooltip]
        images.push(image)
      else
        product.origins.each do |origin|
          tooltip = ""
          case origin.slug
          when "dial_osc"
            tooltip = t("view.product.index.source_dial")
          when "digital_square"
            tooltip = t("view.product.index.source_digital_square")
          when "unicef"
            tooltip = t("view.product.index.source_unicef")
          end
          image = Hash["filename"=>"origins/"+origin.slug+".png", "tooltip"=>tooltip]
          images.push(image)
        end
      end
    end
    images
  end

end

app/views/products/_filter.html.erb
<div class="collapse" id="filter-options">
  <hr />
  <%= form_tag(products_path, :method => "get") do %>
    <%= hidden_field nil, 'filter' %>
    <div class="form-row">
      <div class="col-6 mb-3">
        <fieldset class="form-label-group">
          <%= text_field_tag "search", params[:search],
              placeholder: t('view.general.name'),
              class: "form-control" %>
          <%= label_tag "name", t('view.general.name') %>
        </fieldset>
      </div>
    </div>
    <div class="form-row mb-2">
      <div class="col-12">
        <div class="form-check">
          <%= check_box_tag "has_maturity", true, params[:has_maturity], {class: "form-check-input"} %>
          <%= label_tag "has_maturity", t('view.product.index.has-maturity'), class: "form-check-label" %>
        </div>
      </div>
    </div>
    <div class="form-row">
      <div class="col-6 mb-3">
        <%= label_tag "organizations", t('model.organization').to_s.pluralize.humanize %>
        <%= collection_select(nil, "organizations",
                              Organization.all.order(:name), :id, :name,
                              { selected: params[:organizations] },
                              { multiple: true, class: 'custom-select' }) %>
      </div>
    </div>
  <% end %>
  <hr />
</div>

app/views/products/_launch.html.erb
<p class="card-text text-muted">
  <%= t('view.product.launch.auto-launch') %>
</p>

<div id="launchDiv" style="height:220px;"></div>
<%= content_tag :div, id: "jenkinsData", data: {jenkins_url: @jenkins_url, jenkins_user: @jenkins_user, jenkins_password: @jenkins_password, job_name: @product.slug} do %>
<% end %>

<script>
    launchData.initialize();
</script>

app/views/products/edit.html.erb
<% if @product.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t('view.general.error', count: @product.errors.count) %>
      <% @product.errors.each do |attr, err| %>
        <%= err %>
      <% end %>
    </div>
  </div>
<% end %>
<h5 class="border rounded bg-secondary text-white p-3">
  <%= t('view.general.title.edit', model: t('model.product')) %>
</h5>
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<p class="text-success"><%= flash[:notice] %></p>
<p class="text-danger"><%= flash[:error] %></p>

<div class="row">
  <a href="#" class="prod-show-hide ml-4" id="prod-show-more">
    <p class="float-left mb-0 small"><%= t('view.general.show-product').to_s %></p>
  </a>
  <div id="prod-more" class="hidden">
    <section class="hero bg-secondary mb-2 ml-3 mr-3">
      <div class="col-12 ml-2 mt-2 text-white">
        <h5><strong><%= t('model.product').to_s.titleize.pluralize %></strong></h5>
        <div id="prod-desc">
          <p class="mr-4"><%= t('view.product.index.definition').to_s %></p>
          <div class="row">
            <div class="col-lg-6">
              <%= image_tag("/assets/products/ProductLegend1.png", class: 'card-img-top align-middle p-0') %>
            </div>
            <div class="col-lg-6">
              <%= image_tag("/assets/products/ProductLegend2.png", class: 'card-img-top align-middle p-0') %>
            </div>
          </div>
          <p class="mr-4 mt-2"><%= t('view.product.index.footer_help').to_s %></p>
          <a href="#" id="prod-show-less" class="prod-show-hide hidden">
            <p class="float-left"><%= t('view.general.show-less').to_s %></p>
          </a>
        </div>
      </div>
    </section>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <div class="float-right">
    <%= link_to t('view.product.index.product-graph'), productmap_path, class: 'small mr-1',
                target: "_blank", rel: "noreferrer noopener" %>
    <span class="small mr-1">&nbsp;|</span>
    <% if user_signed_in? && policy(Product).mod_allowed? %>
      <%= link_to t('view.general.create'), new_product_path, class: 'small mr-1' %>
      <span class="small mr-1">&nbsp;|</span>
      <%= link_to t('view.organization.index.view-audit'), audits_path(type: "Product"), :class => 'small mr-1' %>
    <% else %>
      <%= link_to t('view.general.create'),
          'https://github.com/unicef/publicgoods-candidates#how-to-submit-a-new-candidate-for-a-digital-public-good',
          class: 'small mr-1', target: :_blank  %>
    <% end %>
    </div>
  </div>
</div>

<div id="current-list">
<div class="row">
  <% @products.each do |product| %>
    <div class="col-lg-5ths col-md-4 d-flex align-items-stretch mt-2">
      <div class="card index-card small">
        <div class="card-header bg-secondary text-white truncate-parent">
          <%= link_to product.name, product, class: 'truncate-text',
            'title' => product.name, 'data-toggle' => 'tooltip', 'data-placement' => 'top' %>
          <div>
          <% if product.is_launchable %>
            <i class="fa fa-rocket header-img ml-1" data-toggle="tooltip" data-placement="top" data-original-title="<%= t('view.product.index.is_deployable') %>"></i>
          <% end %>
          <% if is_endorsed(product) %>
            <%= image_tag("digiprins.png", class: 'header-img', 'title' => t('view.product.index.is_endorsed'), 'data-toggle' => 'tooltip', 'data-placement' => 'top') %>
          <% end %>
          </div>
        </div>
        <div class="model-logo">
          <%= link_to(product) do %>
            <%= image_tag(product.image_file, class: 'card-img-top align-middle', skip_pipeline: true) %>
          <% end %>
        </div>

        <div class="card-footer footer-padding">
            <% category, images = get_footer_row(product, 1) %>
            <% if images.count > 0 %>
              <div class="footer-row" data-toggle="popover" data-placement="bottom" data-html="true" data-content='<%= get_row_popover(category,images) %>'>
            <% else %>
              <div class="footer-row">
            <% end %>
              <% images.each do |image| %>
                <% if image["gradient"] %>
                  <div class="digisquare-gauge-small" title data-toggle="tooltip" data-placement="top" data-original-title="<%= image["tooltip"] %>">
                    <p class="footer-score"><%= image["filename"] %></p>
                  </div>
                <% elsif image["osc"] %>
                  <div class="osc-small" title data-toggle="tooltip" data-placement="top" data-original-title="<%= image["tooltip"] %>">
                    <p class="osc-footer-score"><%= image["filename"] %></p>
                  </div>
                <% else %>
                  <%= image_tag(image["filename"], class: 'footer-img', 'title' => image["tooltip"], 'data-toggle' => 'tooltip', 'data-placement' => 'top') %>
                <% end %>
              <% end %>
            </div>
            <% category, images = get_footer_row(product, 2) %>
            <% if images.count > 0 %>
              <div class="footer-row mt-1" data-toggle="popover" data-placement="bottom" data-html="true" data-content='<%= get_row_popover(category,images) %>'>
            <% else %>
              <div class="footer-row mt-1">
            <% end %>
              <% images.each do |image| %>
                <% if image["gradient"] %>
                  <div class="digisquare-gauge-small" title data-toggle="tooltip" data-placement="top" data-original-title="<%= image["tooltip"] %>">
                    <p class="footer-score"><%= image["filename"] %></p>
                  </div>
                <% elsif image["osc"] %>
                  <div class="osc-small" title data-toggle="tooltip" data-placement="top" data-original-title="<%= image["tooltip"] %>">
                    <p class="osc-footer-score"><%= image["filename"] %></p>
                  </div>
                <% else %>
                  <%= image_tag(image["filename"], class: 'footer-img', 'title' => image["tooltip"], 'data-toggle' => 'tooltip', 'data-placement' => 'top') %>
                <% end %>
              <% end %>
            </div>
            <% category, images = get_footer_row(product, 3) %>
            <div class="footer-row" data-container="body" data-toggle="popover" data-placement="bottom">
              <p class="footer-source"><%= get_source_label(product) %></p>
              <% images.each do |image| %>
                <%= image_tag(image["filename"], class: 'footer-img-right', 'title' => image["tooltip"], 'data-toggle' => 'tooltip', 'data-placement' => 'top') %>
              <% end %>
            </div>
          </small>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>

<script>
  $(".prod-show-hide").on('click', function(e) {
    e.preventDefault()
    $("#prod-more").toggleClass('hidden')
    $("#prod-show-more").toggleClass('hidden')
    $("#prod-show-less").toggleClass('hidden')
  })
</script>

app/views/products/launch.js.erb
$("#launchdata").html("<%= escape_javascript(render partial: 'products/launch' ) %>");

app/views/products/map.html.erb
<div id="mynetwork" style="width:100%; height:900px"></div>

<script type="text/javascript">
    // create an array with nodes
    var nodes = new vis.DataSet([
    <% @products.each do |product| %>
       <% if !product.include_relationships.empty? or !product.interop_relationships.empty? or !product.references.empty? %>
          {id: <%= product.id %>, label: '<%= product.name %>',value: <%= product.include_relationships.size + product.interop_relationships.size + product.references.size %>},
      <% end %>
    <% end %>
    ]);

    // create an array with edges
    var edges = new vis.DataSet([
    <% @product_relationships.each do |product_rel| %>
        {from: <%= product_rel.from_product.id %>, to: <%= product_rel.to_product.id %>
        <% if product_rel.relationship_type == 'contains' %>
          , color: {color:'#5b90e6', inherit:false}, dashes: false
        <% elsif product_rel.relationship_type == 'interoperates_with' %>
          , color: {color:'#CD6155', inherit:false}, dashes: [5,5] //#64c3ce (teal), #8551ff (tanzanite)
        <% end %>
        },
    <% end %>
    ]);

    // create a network
    var container = document.getElementById('mynetwork');

    // provide the data in the vis format
    var data = {
        nodes: nodes,
        edges: edges
    };
    var options = {
      edges: { arrows: { to: { enabled: true, scaleFactor: .5 } } },
      physics: { repulsion: { nodeDistance: 10 } },
      nodes: {
        shape: 'dot',
        scaling: {
          min: 1,
          max: <%= @products.count / 3 %>
        }
      }
    };

    // initialize your network!
    var network = new vis.Network(container, data, options);
</script>

app/views/products/new.html.erb
<p class="text-danger"><%= flash[:error] %></p>
<% if @product.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t('view.general.error', count: @product.errors.count) %>
    </div>
  </div>
<% end %>
<h5 class="border rounded bg-secondary text-white p-3">
  <%= t('view.general.title.create', model: t('model.product')) %>
</h5>
<%= render 'form', product: @product %>